# Generated by Django 5.1.5 on 2025-01-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
    ]
